# Generated by Django 2.1.7 on 2019-03-07 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='template',
            field=models.CharField(default='post-detail.html', max_length=500, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='post',
            name='add_post',
            field=models.BooleanField(default=True, verbose_name='Опубликовать?'),
        ),
    ]
