# Generated by Django 2.1.7 on 2019-03-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20190307_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='template',
            field=models.CharField(default='post-list.html', max_length=500, verbose_name='Шаблон'),
        ),
        migrations.AddField(
            model_name='post',
            name='displayregister',
            field=models.BooleanField(default=True, verbose_name='Для всех?'),
        ),
        migrations.AlterField(
            model_name='post',
            name='template',
            field=models.CharField(default='post-detail.html', max_length=500, verbose_name='Шаблон'),
        ),
    ]
