# Generated by Django 2.1.7 on 2019-03-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20190310_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='posts_amount',
            field=models.IntegerField(default='5', verbose_name='Количество новостей'),
        ),
    ]
