# Generated by Django 2.1.7 on 2019-03-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_category_posts_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='template',
            field=models.CharField(default='news/post-list.html', max_length=500, verbose_name='Шаблон'),
        ),
    ]
