# Generated by Django 2.1.7 on 2019-03-14 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20190310_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='posts_amount',
        ),
        migrations.AddField(
            model_name='category',
            name='pagination',
            field=models.PositiveIntegerField(default=5, verbose_name='Кол. для пагинации'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='post',
            name='template',
            field=models.CharField(default='news/post-detail.html', max_length=500, verbose_name='Шаблон'),
        ),
    ]
