# Generated by Django 2.1.7 on 2019-03-14 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0007_auto_20190314_2015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='add_post',
            new_name='published',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='displayregister',
        ),
        migrations.RemoveField(
            model_name='post',
            name='edited',
        ),
        migrations.RemoveField(
            model_name='post',
            name='headline',
        ),
        migrations.RemoveField(
            model_name='post',
            name='main_image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='publicated',
        ),
        migrations.RemoveField(
            model_name='post',
            name='template',
        ),
        migrations.AddField(
            model_name='post',
            name='edit_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата редактирования'),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='post/', verbose_name='Главное изображение'),
        ),
        migrations.AddField(
            model_name='post',
            name='mini_text',
            field=models.TextField(default='', max_length=1000, verbose_name='Краткое содержание'),
        ),
        migrations.AddField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата публикации'),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Для зарегистрированных'),
        ),
        migrations.AddField(
            model_name='post',
            name='subtitle',
            field=models.CharField(default='', max_length=100, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='post',
            name='viewed',
            field=models.PositiveIntegerField(default=0, verbose_name='Просмотров'),
        ),
        migrations.AlterField(
            model_name='category',
            name='template',
            field=models.CharField(default='news/post-list.html', max_length=100, verbose_name='Используемый шаблон'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=100, verbose_name='url'),
        ),
    ]
