# Generated by Django 2.1.7 on 2019-03-14 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20190314_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='template',
            field=models.CharField(default='news/post-detail.html', max_length=100, verbose_name='Используемый шаблон'),
        ),
    ]
